[book]
title = "Coding Style Guide"
authors = ["Samantha"]
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/samantha-labs/style-guide"

[output.katex]
[preprocessor.katex]
trust = true
